apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto
  namespace: argocd
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: service-mesh
  source:
    path: service-mesh/resources/emojivoto
    repoURL: https://github.com/leetdx/argocd-application-helm.git
    targetRevision: dev

