apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: service-mesh
  source:
    path: service-mesh/charts/linkerd-crds
    repoURL: https://github.com/leetdx/argocd-application-helm.git
    targetRevision: dev
    helm:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
